# A wrapper workflow that calls down to Kurtosis Release workflow repo
name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      bump_major:
        description: '(DANGER) Bump the MAJOR version ("X" in "X.Y.Z") on this release'
        required: true
        type: boolean
      should_do_weekend_release:
        description: '(DANGER) Override weekend release protection and do a risky release'
        required: true
        type: boolean

jobs:
  weekend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Verify release is allowed (weekend releases are only allowed when weekend release override is set)
        run: |
          set -euo pipefail

          is_weekend_release="false"

          # 'date +%u' returns Monday = 1..... Friday = 5, Sat = 6, Sun = 7
          FRIDAY_ORDINAL=5
          day_of_week_ordinal="$(date +%u)"
          if [ "${day_of_week_ordinal}" -ge "${FRIDAY_ORDINAL}" ]; then
            is_weekend_release="true"
          fi

          if "${is_weekend_release}" && ! ${{ inputs.should_do_weekend_release }}; then
            echo "Refusing to release on Friday, Saturday, or Sunday to avoid risk of Kurtosians needing to fix bugs on the weekend"
            exit 1
          fi
  release:
    uses: kurtosis-tech/release/.github/workflows/release.yml@master
    with:
      bump_major: ${{ inputs.bump_major }}
    secrets: inherit
    needs: weekend-check
